jadwaldokter/urls.py
from django.urls import path

from . import views

app_name = 'jadwaldokter'

urlpatterns = [
    path('lihat/', views.jadwaldokter_lihat, name='jadwaldokter_lihat'),
    path('lihat/buat/', views.jadwaldokter_buat, name='jadwaldokter_buat'),
    path('lihat/buat/<int:pk>', views.jadwaldokter_create, name='jadwaldokter_create'),


]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sirucoc08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),name="main"),
    path('jadwal/', include('jadwal.urls'),name="jadwal"),
    path('user/', include('user.urls'),name="user"),
    path('profil/', include('profil.urls'),name="profil"),
    path('ruanghotel/', include('ruanganhotel.urls'),name="ruanganhotel"),
    path('appoinment/', include('appoinment.urls'),name="appoinment"),
    path('ruanganrs/', include('ruanganrs.urls'),name="ruanganrs"),
    path('faskes/', include('faskes.urls'),name="faskes"),
    path('jadwaldokter/', include('jadwaldokter.urls'),name="jadwaldokter"),
    path('reservasirs/', include('reservasirumahsakit.urls'),name="reservasirs"),
    path('transaksirs/', include('transaksirumahsakit.urls'),name="transaksirs"),
    path('rumahsakit/', include('rumahsakit.urls'),name="rumahsakit"),
    path('reservasihotel/', include('reservasihotel.urls'),name="reservasihotel"),
    path('transaksihotel/', include('transaksihotel.urls'),name="transaksihotel"),
    path('transaksibooking/', include('transaksibooking.urls'),name="transaksibooking"),
    path('pasien/', include('pasien.urls'),name="pasien"),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('transaksimakan/', include('transaksimakan.urls'), name="transaksimakan"),
]

jadwaldokter/models.py
from django.db import models

# Create your models here.

jadwaldokter/views.py
from django.shortcuts import render,redirect
from django.db import connection
from collections import namedtuple
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect


def jadwaldokter_lihat(request):
	if(request.session['role']=='dokter'):
		cursor = connection.cursor()
		cursor.execute("select * from SIRUCO.jadwal_dokter WHERE username='{}';".format(request.session['email']))
		data_jadwal = fetch(cursor)
		return render(request, 'jadwaldokter.html', {'data_jadwal':data_jadwal})
	elif(request.session['role']=='admin satgas' or request.session['role']=='Pengguna Publik'):
		cursor = connection.cursor()
		cursor.execute("select * from SIRUCO.jadwal_dokter;")
		data_jadwal = fetch(cursor)
		return render(request, 'jadwaldokter2.html', {'data_jadwal':data_jadwal})
	else:
		return render(request, 'tolakjadwal.html')


def jadwaldokter_buat(request):
	cursor = connection.cursor()
	cursor.execute("select * from SIRUCO.jadwal;")
	data_jadwal = fetch(cursor)
	# if request.method == 'POST':	
	# 	kodefaskes = request.POST.get('kode_faskes')
	# 	shift = request.POST.get('shift')
	# 	tanggal = request.POST.get('tanggal')
	# 	jmlpasien = request.POST.get('jmlpasien')
	# 	print(kodefaskes,shift,tanggal)
	# 	return redirect('/')

	return render(request, 'buatjadwal.html', {'data_jadwal':data_jadwal})

def jadwaldokter_create(request,pk):
	message=""
	cursor = connection.cursor()
	# cursor.execute("SET search_path TO siruco;")
	cursor.execute("select * from SIRUCO.jadwal;")
	data_jadwal = fetch(cursor)[pk-1]
	cursor.execute("SELECT * FROM siruco.dokter WHERE username='{}';".format(request.session['email']))
	data_dokter= fetch(cursor)[0]

	try:
		cursor.execute("INSERT INTO SIRUCO.jadwal_dokter(NoSTR, Username, Kode_Faskes,Shift, Tanggal,JmlPasien)"
		"VALUES ('{}', '{}', '{}', '{}', '{}', '{}');".format(data_dokter['nostr'],data_dokter['username'],data_jadwal['kode_faskes'], data_jadwal['shift'],data_jadwal['tanggal'],0))
	# if request.method == 'POST':	
	# 	kodefaskes = request.POST.get('kode_faskes')
	# 	shift = request.POST.get('shift')
	# 	tanggal = request.POST.get('tanggal')
	# 	jmlpasien = request.POST.get('jmlpasien')
	# 	print(kodefaskes,shift,tanggal)
	except Exception as e:
            print("waw")
            message=str(e)[0:29]	
	args={
        'message':message,
    }
	return render(request, 'confirm.html',args)





def fetch(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

def get_as_dict(cursor):
    columns = [column[0] for column in cursor.description]
    results = []
    for row in cursor.fetchall():
        results.append(dict(zip(columns, row)))
    return results

jadwaldokter/templates/buatjadwal.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center>List Jadwal Dokter</center></h2>
  <div class="pt-5 pl-2">
  </div>
  <div class="pt-2">
  <table class="table">
  <thead>
    <tr class="table-primary">
      <th scope="col">No.</th>
      <th scope="col">Faskes</th>
      <th scope="col">Shift</th>
      <th scope="col">Tanggal</th>
      <th scope="col">Buat Jadwal</th>
    </tr>
  </thead>
  <tbody>
          {% for list in data_jadwal %} 
          <!-- {% csrf_token %} -->
            <tr>
            	  <td>{{ forloop.counter }}</td>
                <td>{{ list.kode_faskes }}</td>
                <td>{{ list.shift }}</td>
                <td>{{ list.tanggal }}</td>
                <td><a href="{% url 'jadwaldokter:jadwaldokter_create' pk=forloop.counter%}" class="btn btn-primary">Buat</button></td>
            </tr>
           {% endfor %}
   </tbody>

  </table>
</div>

{% endblock content %}

jadwaldokter/templates/confirm.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center>List Jadwal Dokter</center></h2>
  <div class="pt-5 pl-2">
  </div>
  <div class="pt-2">
    <h2><center>{{ message }}</center></h2>

    <h2><center>Kembali ke List Jadwal</center></h2>
    <div class="pt-2">
    </div>
    </div>
        <center><a href="{% url 'jadwaldokter:jadwaldokter_lihat' %}" class="btn btn-primary">Kembali</a></center>
  


{% endblock content %}

jadwaldokter/templates/jadwaldokter.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center>List Jadwal Dokter</center></h2>
  <div class="pt-5 pl-2">
    <a href="{% url 'jadwaldokter:jadwaldokter_buat' %}" type="button" class="btn btn-info">Buat Jadwal Dokter</a>
  </div>
  <div class="pt-2">
  <table class="table">
  <thead>
    <tr class="table-primary">
      <th scope="col">No.</th>
      <th scope="col">No STR</th>
      <th scope="col">Dokter</th>
      <th scope="col">Faskes</th>
      <th scope="col">Shift</th>
      <th scope="col">Tanggal</th>
      <th scope="col">Jumlah Pasien</th>
    </tr>
  </thead>
  <tbody>
          {% for list in data_jadwal %}
            <tr>
            	  <td>{{ forloop.counter }}</td>
                <td>{{ list.nostr }}</td>
                <td>{{ list.username }}</td>
                <td>{{ list.kode_faskes }}</td>
                <td>{{ list.shift }}</td>
                <td>{{ list.tanggal }}</td>
                <td>{{ list.jmlpasien }}</td>
            </tr>
           {% endfor %}
   </tbody>

  </table>
</div>

{% endblock content %}

jadwaldokter/templates/jadwaldokter2.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center>List Jadwal Dokter</center></h2>
  <div class="pt-2">
  <table class="table">
  <thead>
    <tr class="table-primary">
      <th scope="col">No.</th>
      <th scope="col">No STR</th>
      <th scope="col">Dokter</th>
      <th scope="col">Faskes</th>
      <th scope="col">Shift</th>
      <th scope="col">Tanggal</th>
      <th scope="col">Jumlah Pasien</th>
    </tr>
  </thead>
  <tbody>
          {% for list in data_jadwal %}
            <tr>
            	  <td>{{ forloop.counter }}</td>
                <td>{{ list.nostr }}</td>
                <td>{{ list.username }}</td>
                <td>{{ list.kode_faskes }}</td>
                <td>{{ list.shift }}</td>
                <td>{{ list.tanggal }}</td>
                <td>{{ list.jmlpasien }}</td>
            </tr>
           {% endfor %}
   </tbody>

  </table>
</div>


{% endblock content %}

jadwaldokter/templates/tolakjadwal.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center></center></h2>
  <div class="pt-5 pl-2">
  </div>
  <div class="pt-2">
    <h2><center>Anda tidak memiliki akses!!</center></h2>

    <h2><center>Kembali ke laman utama</center></h2>
    <div class="pt-2">
        </div>
        </div>
        <center><a href="/" class="btn btn-primary">Kembali</a></center>
  
  


{% endblock content %}