main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sirucoc08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),name="main"),
    path('jadwal/', include('jadwal.urls'),name="jadwal"),
    path('user/', include('user.urls'),name="user"),
    path('profil/', include('profil.urls'),name="profil"),
    path('ruanghotel/', include('ruanganhotel.urls'),name="ruanganhotel"),
    path('appoinment/', include('appoinment.urls'),name="appoinment"),
    path('ruanganrs/', include('ruanganrs.urls'),name="ruanganrs"),
    path('faskes/', include('faskes.urls'),name="faskes"),
    path('jadwaldokter/', include('jadwaldokter.urls'),name="jadwaldokter"),
    path('reservasirs/', include('reservasirumahsakit.urls'),name="reservasirs"),
    path('transaksirs/', include('transaksirumahsakit.urls'),name="transaksirs"),
    path('rumahsakit/', include('rumahsakit.urls'),name="rumahsakit"),
    path('reservasihotel/', include('reservasihotel.urls'),name="reservasihotel"),
    path('transaksihotel/', include('transaksihotel.urls'),name="transaksihotel"),
    path('transaksibooking/', include('transaksibooking.urls'),name="transaksibooking"),
    path('pasien/', include('pasien.urls'),name="pasien"),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('transaksimakan/', include('transaksimakan.urls'), name="transaksimakan"),
]

transaksihotel/urls.py
from django.urls import path

from . import views

app_name = 'transaksihotel'

urlpatterns = [
    path('', views.read_transaksi_hotel, name='read_transaksi_hotel'),
    path('update/<str:idtransaksi>', views.update_transaksi_hotel, name='update_transaksi_hotel'),
]

transaksimakan/urls.py
from django.urls import path

from . import views

app_name = 'transaksimakan'

urlpatterns = [
    path('read/', views.transaksi_makan_read, name='transaksi_makan_read'),
    path('create/', views.transaksi_makan_create, name='transaksi_makan_read'),
    path('update/', views.transaksi_makan_update, name='transaksi_makan_update'),
    path('delete/', views.transaksi_makan_delete, name='transaksi_makan_delete'),
]

transaksimakan/models.py
from django.db import models

# Create your models here.

transaksimakan/forms.py
from django import forms
from django.db import connection
from django.core.paginator import Paginator

class updatetransaksi(forms.Form):
    statusbayar = forms.CharField(label='Jenis Bed', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})

transaksimakan/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *


def fetch(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

def transaksi_makan_read(request):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    role = request.session['role']
    if (role == "admin satgas" or role == "Pengguna Publik"):
        cursor = connection.cursor()
        cursor.execute("select * from SIRUCO.daftar_pesan")
        data_transaksi = fetch(cursor)
        return render(request, 'transaksimakanlst.html', {'data_transaksi':data_transaksi})

def transaksi_makan_create(request):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    if (role == "admin satgas" or role == "Pengguna Publik"):

        return render(request, 'transaksimakancrt.html')

def transaksi_makan_update(request):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    if (role == "admin satgas"):


        return render(request,'transaksimakanupd.html')
    else:
        return HttpResponseRedirect('/profil/profil')

def transaksi_makan_delete(request):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    if (role == "admin satgas"):

        return render(request,'transaksimakandlt.html')
    else:
        return HttpResponseRedirect('/profil/profil')

transaksimakan/templates/transaksimakancrt.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Create Transaksi Hotel</title>
{% endblock meta %}

{% block content %}
<div class="card">
	<div class='text-center'>
    <div class="card-header">
      Harap Isi Form 
    </div>
	</div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <h4><center>Update Transaksi Hotel</center></h4>
      <form action="{% url 'transaksihotel:update_transaksi_hotel' idtransaksi=lama.idtransaksi %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault05">NIK Pasien</label>
              <p>{{lama.kodepasien}}</p>
          </div>
          <div class="form-group">
            <label for="validationDefault05">Id Transaksi</label>
              <p>{{lama.idtransaksi}}</p>
          </div>
          
          <div class="form-group">
            <label for="exampleInputEmail1">Tanggal Pembayaran</label>
            <p>{{ lama.tanggalpembayaran }}</p>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Waktu Pembayaran</label>
            <p>{{ lama.waktupembayaran }}</p>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Total Biaya</label>
            <p>Rp{{ lama.totalbayar }}</p>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Status Pembayaran</label>
            {{ form.statusbayar }}
          </div>
    
          <button type="submit" class="btn btn-primary  btn-am">Simpan</button>
      </form>
      </div>
    </div>
  </div>

{% endblock content %}

transaksimakan/templates/transaksimakanlst.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Transaksi Makan</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center>List Transaksi Hotel</center></h2>
  <div class="pt-2">
  <table class="table">
  <thead>
    <tr class="table-primary">
      <th scope="col">No.</th>
      <th scope="col">Id Transaksi Hotel</th>
      <th scope="col">Id Transaksi</th>
      <th scope="col">Total Bayar</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
          {% for d in data_transaksi %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ d.idtransaksi }}</td>
                <td>{{ d.idtransaksimakan }}</td>
                <td>{{ d.totalbayar }}</td>
                <td>
                  <div class="pi-draggable btn-group" draggable="true">
                  <a class="btn btn-primary" href="{% url 'transaksimakan:transaksi_makan_detail' idtransaksi=d.idtransaksi idtransaksimakan=d.idtransaksimakan %}"><b>detail</b></a>
                  {% if role == 'admin satgas' %}
                   <a class="btn btn-primary" href="{% url 'transaksimakan:transaksi_makan_update' idtransaksi=d.idtransaksi idtransaksimakan=d.idtransaksimakan %}"><b>update</b></a>
                   <a class="btn btn-primary" href="{% url 'transaksimakan:transaksi_makan_delete' idtransaksi=d.idtransaksi idtransaksimakan=d.idtransaksimakan %}"><b>delete</b></a>
                </div>
                </td>
            </tr>
           {% endfor %}
   </tbody>

  </table>
</div>

{% endblock content %}

transaksimakan/templates/transaksimakanupd.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Update Transaksi Makan</title>
{% endblock meta %}

{% block content %}
<div class="card">
	<div class='text-center'>
    <div class="card-header">
      Harap Isi Form 
    </div>
	</div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <h4><center>Update Transaksi Hotel</center></h4>
      <form action="{% url 'transaksihotel:update_transaksi_hotel' idtransaksi=lama.idtransaksi %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault05">NIK Pasien</label>
              <p>{{lama.kodepasien}}</p>
          </div>
          <div class="form-group">
            <label for="validationDefault05">Id Transaksi</label>
              <p>{{lama.idtransaksi}}</p>
          </div>
          
          <div class="form-group">
            <label for="exampleInputEmail1">Tanggal Pembayaran</label>
            <p>{{ lama.tanggalpembayaran }}</p>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Waktu Pembayaran</label>
            <p>{{ lama.waktupembayaran }}</p>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Total Biaya</label>
            <p>Rp{{ lama.totalbayar }}</p>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Status Pembayaran</label>
            {{ form.statusbayar }}
          </div>
    
          <button type="submit" class="btn btn-primary  btn-am">Simpan</button>
      </form>
      </div>
    </div>
  </div>

{% endblock content %}