main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

pasien/urls.py
from django.urls import path

from . import views

app_name = 'pasien'

urlpatterns = [
    path('', views.pasien_lihat, name='pasien_lihat'),
    path('buat/', views.pasien_buat, name='pasien_buat'),
    path('update/<str:nik>/', views.pasien_update, name='pasien_update'),
    path('detail/<str:nik>/', views.pasien_detail, name='pasien_detail'),
    path('hapus/<str:nik>/', views.pasien_hapus, name='pasien_hapus')
]

sirucoc08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),name="main"),
    path('jadwal/', include('jadwal.urls'),name="jadwal"),
    path('user/', include('user.urls'),name="user"),
    path('profil/', include('profil.urls'),name="profil"),
    path('ruanghotel/', include('ruanganhotel.urls'),name="ruanganhotel"),
    path('appoinment/', include('appoinment.urls'),name="appoinment"),
    path('ruanganrs/', include('ruanganrs.urls'),name="ruanganrs"),
    path('faskes/', include('faskes.urls'),name="faskes"),
    path('jadwaldokter/', include('jadwaldokter.urls'),name="jadwaldokter"),
    path('reservasirs/', include('reservasirumahsakit.urls'),name="reservasirs"),
    path('transaksirs/', include('transaksirumahsakit.urls'),name="transaksirs"),
    path('rumahsakit/', include('rumahsakit.urls'),name="rumahsakit"),
    path('reservasihotel/', include('reservasihotel.urls'),name="reservasihotel"),
    path('transaksihotel/', include('transaksihotel.urls'),name="transaksihotel"),
    path('transaksibooking/', include('transaksibooking.urls'),name="transaksibooking"),
    path('pasien/', include('pasien.urls'),name="pasien"),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('transaksimakan/', include('transaksimakan.urls'), name="transaksimakan"),
]

pasien/models.py
from django.db import models

# Create your models here.

pasien/forms.py
from django import forms
from django.db import connection
from django.core.paginator import Paginator


class buatpasien(forms.Form):
    nik = forms.CharField(label='NIK', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    nama = forms.CharField(label='Nama', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    notelp = forms.CharField(label='No Telepon', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    nohp = forms.CharField(label='No HP', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_jalan = forms.CharField(label='Jalan', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_kelurahan = forms.CharField(label='Kelurahan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_kecamatan = forms.CharField(label='Kecamatan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_kabkot = forms.CharField(label='Kabupaten/Kota',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_prov = forms.CharField(label='Provinsi',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_jalan = forms.CharField(label='Jalan', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_kelurahan = forms.CharField(label='Kelurahan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_kecamatan = forms.CharField(label='Kecamatan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_kabkot = forms.CharField(label='Kabupaten/Kota',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_prov = forms.CharField(label='Provinsi',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})

class updatepasien(forms.Form):
    nik = forms.CharField(label='NIK', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    nama = forms.CharField(label='Nama', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    notelp = forms.CharField(label='No Telepon', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    nohp = forms.CharField(label='No HP', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_jalan = forms.CharField(label='Jalan', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_kelurahan = forms.CharField(label='Kelurahan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_kecamatan = forms.CharField(label='Kecamatan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_kabkot = forms.CharField(label='Kabupaten/Kota',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    ktp_prov = forms.CharField(label='Provinsi',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_jalan = forms.CharField(label='Jalan', widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_kelurahan = forms.CharField(label='Kelurahan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_kecamatan = forms.CharField(label='Kecamatan',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_kabkot = forms.CharField(label='Kabupaten/Kota',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})
    dom_prov = forms.CharField(label='Provinsi',  widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, error_messages = {'required': "Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu"})

pasien/views.py
from pasien.forms import buatpasien, updatepasien
from django.shortcuts import render,redirect
from django.db import connection
from collections import namedtuple
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect, response
# from .forms import *

def fetch(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

def get_as_dict(cursor):
    columns = [column[0] for column in cursor.description]
    results = []
    for row in cursor.fetchall():
        results.append(dict(zip(columns, row)))
    return results

def pasien_lihat(request):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    role = request.session['role']
    if (role == 'Pengguna Publik'):
        idpendaftar = request.session['email']
        cursor = connection.cursor()
        cursor.execute("select * from SIRUCO.pasien where idpendaftar = '{}'".format(idpendaftar))
        data_pasien = fetch(cursor)
        return render(request, 'pasien.html', {'data_pasien':data_pasien, 'role':role})

    else:
        return HttpResponseRedirect('/user/login')
	

def pasien_buat(request):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    role = request.session['role']
    if (role == 'Pengguna Publik'): 
        email = request.session['email'].split('@')
        idpendaftar = email[0]
        if request.method == 'POST':
            form = buatpasien(request.POST)
            if form.is_valid():
                nik = request.POST.get('nik')
                nama = request.POST.get('nama')
                notelp = request.POST.get('notelp')
                nohp = request.POST.get('nohp')
                ktp_jalan = request.POST.get('ktp_jalan')
                ktp_kelurahan = request.POST.get('ktp_kelurahan')
                ktp_kecamatan = request.POST.get('ktp_kecamatan')
                ktp_kabkot = request.POST.get('ktp_kabkot')
                ktp_prov = request.POST.get('ktp_prov')
                dom_jalan = request.POST.get('dom_jalan')
                dom_kelurahan = request.POST.get('dom_kelurahan')
                dom_kecamatan = request.POST.get('dom_kecamatan')
                dom_kabkot = request.POST.get('dom_kabkot')
                dom_prov = request.POST.get('dom_prov')
                with connection.cursor() as c: 
                    c.execute("INSERT INTO SIRUCO.pasien VALUES ('{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}','{}')".format(nik, idpendaftar, nama, ktp_jalan,ktp_kelurahan,ktp_kecamatan,ktp_kabkot,ktp_prov,dom_jalan,dom_kelurahan,dom_kecamatan,dom_kabkot,dom_prov, notelp, nohp))
            return HttpResponseRedirect(reverse('pasien:pasien_lihat'))
        form = buatpasien()
        return render(request, 'buatpasien.html', {'form':form, 'data':idpendaftar})

def pasien_detail(request, nik):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    role = request.session['role']
    if (role == 'Pengguna Publik'):
        with connection.cursor() as c:
            c.execute("SELECT * FROM SIRUCO.pasien WHERE nik = '{}'".format(nik))
            data = fetch(c)
            c.execute("SELECT * FROM SIRUCO.pengguna_publik B, SIRUCO.pasien P WHERE P.idpendaftar = B.username and P.nik = '{}'".format(nik))
            data2 = fetch(c)
        initial_data = {
            'nik' : data[0]['nik'],
            'idpendaftar' : data[0]['idpendaftar'],
            'nama' : data[0]['nama'],
            'ktp_jalan' : data[0]['ktp_jalan'],
            'ktp_kelurahan' : data [0]['ktp_kelurahan'],
            'ktp_kecamatan' : data [0]['ktp_kelurahan'],
            'ktp_kabkot' : data [0]['ktp_kabkot'],
            'ktp_prov' : data [0]['ktp_prov'],
            'dom_jalan' : data [0]['dom_jalan'],
            'dom_kelurahan' : data [0]['dom_kelurahan'],
            'dom_kecamatan' : data [0]['dom_kecamatan'],
            'dom_kabkot' : data [0]['dom_kabkot'],
            'dom_prov' : data [0]['dom_prov'],
            'notelp' : data [0]['notelp'],
            'nohp' : data [0]['nohp']
        }

        initial_data2 = {
            'username' : data2[0]['username']
        }
        response = {'data': initial_data, 'data2': initial_data2}
        return render(request,'detailpasien.html', response)
    else:
        return HttpResponseRedirect(reverse('pasien:pasien_lihat'))

def pasien_update(request, nik):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    role = request.session['role']
    if (role == 'Pengguna Publik'):
        with connection.cursor() as c:
            c.execute("SELECT * FROM SIRUCO.pasien WHERE nik = '{}'".format(nik))
            data = fetch(c)
        initial_data = {
            'nik' : data[0]['nik'],
            'idpendaftar' : data[0]['idpendaftar'],
            'nama' : data[0]['nama'],
            'ktp_jalan' : data[0]['ktp_jalan'],
            'ktp_kelurahan' : data [0]['ktp_kelurahan'],
            'ktp_kecamatan' : data [0]['ktp_kelurahan'],
            'ktp_kabkot' : data [0]['ktp_kabkot'],
            'ktp_prov' : data [0]['ktp_prov'],
            'dom_jalan' : data [0]['dom_jalan'],
            'dom_kelurahan' : data [0]['dom_kelurahan'],
            'dom_kecamatan' : data [0]['dom_kecamatan'],
            'dom_kabkot' : data [0]['dom_kabkot'],
            'dom_prov' : data [0]['dom_prov'],
            'notelp' : data [0]['notelp'],
            'nohp' : data [0]['nohp']
        }
        if request.method == 'POST':
            form = updatepasien(request.POST)
            if form.is_valid():
                nik = request.POST.get('nik')
                nama = request.POST.get('nama')
                notelp = request.POST.get('notelp')
                nohp = request.POST.get('nohp')
                ktp_jalan = request.POST.get('ktp_jalan')
                ktp_kelurahan = request.POST.get('ktp_kelurahan')
                ktp_kecamatan = request.POST.get('ktp_kecamatan')
                ktp_kabkot = request.POST.get('ktp_kabkot')
                ktp_prov = request.POST.get('ktp_prov')
                dom_jalan = request.POST.get('dom_jalan')
                dom_kelurahan = request.POST.get('dom_kelurahan')
                dom_kecamatan = request.POST.get('dom_kecamatan')
                dom_kabkot = request.POST.get('dom_kabkot')
                dom_prov = request.POST.get('dom_prov')
                
                c = connection.cursor()
                c.execute("UPDATE SIRUCO.pasien SET nik = '{}', nama = '{}', notelp = '{}', nohp = '{}', ktp_jalan = '{}', ktp_kelurahan = '{}', ktp_kecamatan = '{}', ktp_kabkot = '{}', ktp_prov = '{}', dom_jalan = '{}', dom_kelurahan = '{}', dom_kecamatan = '{}', dom_kabkot = '{}', dom_prov = '{}' WHERE nik = '{}';".format(nik, nama, notelp, nohp, ktp_jalan, ktp_kelurahan, ktp_kecamatan, ktp_kabkot, ktp_prov, dom_jalan, dom_kelurahan, dom_kecamatan, dom_kabkot, dom_prov, nik))
                
                return HttpResponseRedirect(reverse('pasien:pasien_lihat'))

        update = updatepasien(initial = initial_data)
        response = {'form':update, 'lama':initial_data}
        return render(request,'updatepasien.html',response)
    else:
        return HttpResponseRedirect(reverse('pasien:pasien_lihat'))

def pasien_hapus(request, nik):
    if 'email' not in request.session:
        return HttpResponseRedirect('/user/login')
    role = request.session['role']
    if (role == 'Pengguna Publik'):
        with connection.cursor() as c:
            c.execute("delete from SIRUCO.pasien where nik= '{}'".format(nik))
        return HttpResponseRedirect(reverse('pasien:pasien_lihat'))
    else:
        return HttpResponseRedirect(reverse('pasien:pasien_lihat'))

pasien/templates/buatpasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Pasien</title>
{% endblock meta %}

{% block content %}
<div class="card">
	<div class='text-center'>
    <div class="card-header">
      Harap Isi Form 
    </div>
	</div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <h4><center>Pendaftaran Pasien</center></h4><br>
      <form action="{% url 'pasien:pasien_buat' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault05">Pendaftar:</label>
              <p>{{data}}</p>
          </div>
          <div class="form-group">
            <label for="validationDefault05">NIK:</label>
            {{ form.nik }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Nama:</label>
            {{ form.nama }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Nomor Telepon:</label>
            {{ form.notelp }}
          </div>
          <div class="form-group">
            <label for="validationDefault05">Nomor HP:</label>
            {{ form.nohp }}
          </div><br>
          <br>
          <div class="form-group">
            <label for="exampleInputPassword1">Alamat (Sesuai KTP):</label>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Jalan:</label>
            {{ form.ktp_jalan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kelurahan:</label>
            {{ form.ktp_kelurahan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kecamatan:</label>
            {{ form.ktp_kecamatan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kabupaten/Kota:</label>
            {{ form.ktp_kabkot }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Provinsi:</label>
            {{ form.ktp_prov }}
          </div><br><br>
          <div class="form-group">
            <label for="exampleInputPassword1">Alamat (Domisili):</label>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Jalan:</label>
            {{ form.dom_jalan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kelurahan:</label>
            {{ form.dom_kelurahan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kecamatan:</label>
            {{ form.dom_kecamatan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kabupaten/Kota:</label>
            {{ form.dom_kabkot }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Provinsi:</label>
            {{ form.dom_prov }}
          </div>
    
          <button type="submit" class="btn btn-primary  btn-am">Simpan</button>
      </form>
      </div>
    </div>
  </div>

{% endblock content %}

pasien/templates/detailpasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Detail Pasien</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center>Detail Pasien</center></h2>
  <div class="pt-2">
  <table class="table table-borderless">
    <tbody>
      <tr>
        <td>Pendaftar: {{ data2.username }}</td>
      </tr>
      <tr>
        <td>NIK: {{ data.nik }}</td>
      </tr>
      <tr>
        <td>Nama: {{ data.nama }}</td>
      </tr>
      <tr>
        <td>Nomor Telepon: {{ data.notelp }}</td>
      </tr>
      <tr>
        <td>Nomor HP: {{ data.nohp }}</td>
      </tr>
      <tr>
        <td><br>Alamat (Sesuai KTP):</td>
      </tr>
      <tr>
        <td>&emsp;Jalan: {{ data.ktp_jalan }}</td>
      </tr>
      <tr>
        <td>&emsp;Kelurahan: {{ data.ktp_kelurahan }}</td>
      </tr>
      <tr>
        <td>&emsp;Kecamatan: {{ data.ktp_kecamatan }}</td>
      </tr>
      <tr> 
        <td>&emsp;Kabupaten/Kota: {{ data.ktp_kabkot }}</td>
      </tr>
      <tr>
        <td>&emsp;Provinsi: {{ data.ktp_prov }}</td>
      </tr>
      <tr>
        <td><br>Alamat (Domisili):</td>
      </tr>
      <tr>
        <td>&emsp;Jalan: {{ data.dom_jalan }}</td>
      </tr>
      <tr>
        <td>&emsp;Kelurahan: {{ data.dom_kelurahan }}</td>
      </tr>
      <tr>
        <td>&emsp;Kecamatan: {{ data.dom_kecamatan }}</td>
      </tr>
      <tr> 
        <td>&emsp;Kabupaten/Kota: {{ data.dom_kabkot }}</td>
      </tr>
      <tr>
        <td>&emsp;Provinsi: {{ data.dom_prov }}</td>
      </tr>
      <tr>
        <td class="text-center"><a href="/pasien/"><button type="button" class="btn btn-danger">Kembali</button></a></td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

pasien/templates/pasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>List Fasilitas Kesehatan</title>
<style>
    tr{
        color: #656566;
    }
</style>

{% endblock meta %}

{% block content %}
  <h2><center>List Pasien</center></h2>
  <div class="pt-5 pl-2">
    
  </div>
  <div class="pt-2">
  <table class="table">
  <thead>
    <tr class="table-primary">
      <th scope="col">No.</th>
      <th scope="col">NIK</th>
      <th scope="col">Nama Pasien</th>
      <th scope="col" class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
          {% for list in data_pasien %}
            <tr>
            	  <td>{{ forloop.counter }}</td>
                <td>{{ list.nik }}</td>
                <td>{{ list.nama }}</td>
                <td class="text-center">
                  <div class="pi-draggable btn-group" draggable="true">
                  <a class="btn btn-primary" href="{% url 'pasien:pasien_update' nik=list.nik %}"><b>Update</b></a>
                  <a class="btn btn-success" href="{% url 'pasien:pasien_detail' nik=list.nik %}"><b>Detail</b></a>
                  <a class="btn btn-danger" href="{% url 'pasien:pasien_hapus' nik=list.nik %}"><b>Delete</b></a>
                </td>
            </tr>
           {% endfor %}
   </tbody>

  </table>
</div>

{% endblock content %}

pasien/templates/updatepasien.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Update Pasien</title>
{% endblock meta %}

{% block content %}
<div class="card">
	<div class='text-center'>
    <div class="card-header">
      Harap Isi Form 
    </div>
	</div>
    <div class="card-body form_bg_color ">
      <div class="outer-form container form-column col-md-4 ">
        <h4><center>Update Data Pasien</center></h4><br>
      <form action="{% url 'pasien:pasien_update' nik=lama.nik %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="validationDefault05">Pendaftar:</label>
              <p>{{data}}</p>
          </div>
          <div class="form-group">
            <label for="validationDefault05">NIK:</label>
            {{ form.nik }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Nama:</label>
            {{ form.nama }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Nomor Telepon:</label>
            {{ form.notelp }}
          </div>
          <div class="form-group">
            <label for="validationDefault05">Nomor HP:</label>
            {{ form.nohp }}
          </div><br>
          <br>
          <div class="form-group">
            <label for="exampleInputPassword1">Alamat (Sesuai KTP):</label>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Jalan:</label>
            {{ form.ktp_jalan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kelurahan:</label>
            {{ form.ktp_kelurahan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kecamatan:</label>
            {{ form.ktp_kecamatan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kabupaten/Kota:</label>
            {{ form.ktp_kabkot }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Provinsi:</label>
            {{ form.ktp_prov }}
          </div><br><br>
          <div class="form-group">
            <label for="exampleInputPassword1">Alamat (Domisili):</label>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Jalan:</label>
            {{ form.dom_jalan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kelurahan:</label>
            {{ form.dom_kelurahan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kecamatan:</label>
            {{ form.dom_kecamatan }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Kabupaten/Kota:</label>
            {{ form.dom_kabkot }}
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Provinsi:</label>
            {{ form.dom_prov }}
          </div>
    
          <button type="submit" class="btn btn-primary  btn-am">Simpan</button>
      </form>
      </div>
    </div>
  </div>

{% endblock content %}