main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sirucoc08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),name="main"),
    path('jadwal/', include('jadwal.urls'),name="jadwal"),
    path('user/', include('user.urls'),name="user"),
    path('profil/', include('profil.urls'),name="profil"),
    path('ruanghotel/', include('ruanganhotel.urls'),name="ruanganhotel"),
    path('appoinment/', include('appoinment.urls'),name="appoinment"),
    path('ruanganrs/', include('ruanganrs.urls'),name="ruanganrs"),
    path('faskes/', include('faskes.urls'),name="faskes"),
    path('jadwaldokter/', include('jadwaldokter.urls'),name="jadwaldokter"),
    path('reservasirs/', include('reservasirumahsakit.urls'),name="reservasirs"),
    path('transaksirs/', include('transaksirumahsakit.urls'),name="transaksirs"),
    path('rumahsakit/', include('rumahsakit.urls'),name="rumahsakit"),
    path('reservasihotel/', include('reservasihotel.urls'),name="reservasihotel"),
    path('transaksihotel/', include('transaksihotel.urls'),name="transaksihotel"),
    path('transaksibooking/', include('transaksibooking.urls'),name="transaksibooking"),
    path('pasien/', include('pasien.urls'),name="pasien"),
    path('hotel/', include('hotel.urls'), name="hotel"),
    path('transaksimakan/', include('transaksimakan.urls'), name="transaksimakan"),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('regist/', views.regist, name='regist'),
    path('logout/', views.logout, name='logout'),
    path('regist/sistem/', views.regist_sistem, name='sistem'),
    path('regist/dokter', views.regist_dokter, name='dokter'),
    path('regist/pengguna', views.regist_pengguna, name='pengguna'),
    path('regist/satgas', views.regist_satgas, name='satgas'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.urls import reverse


def home(request):
    if 'email' in request.session:
	    return redirect(reverse('profil:profil'))
    return render(request, 'main/home.html')

main/templates/main/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
 
</head>
<title>SIRUCO</title>

<body>
  <header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">SIRUCO</a>
  </nav>
  </header>

  <div class="pt-5">
    <div class="text-center pt-5">
      <h1>Selamat Datang di SIRUCO!</h1>
      <br>
    <a href="{% url 'user:login' %}" type="button" class="btn btn-info">Login</a>
    <a href="{% url 'user:regist' %}" type="button" class="btn btn-info">Register</a>
    </div>
  </div>
  </div>
</body>